### ISSUE TITLE
import rouge - syntax error in rouge.py

### ISSUE THREAD

**Issue by KavishBhatia** [Diego999/py-rouge#3]
>>> import rouge
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kavish/IAS/KP/Seminar/summary_tool/goose/local/lib/python2.7/site-packages/rouge/__init__.py", line 1, in <module>
    from rouge.rouge import Rouge
  File "/home/kavish/IAS/KP/Seminar/summary_tool/goose/local/lib/python2.7/site-packages/rouge/rouge.py", line 477
    scores = {**scores, **self._get_scores_rouge_n(hypothesis, references)}
               ^
SyntaxError: invalid syntax

**Comment by MarkusZopf** [comment]
The issue has already been resolved by commit https://github.com/Diego999/py-rouge/commit/03029b3b7f5f49b0faf8c50bd17b823361629b0c. It works if you uninstall the pip installation and install it manually as described in the README.
